module.exports = function () {
  return {
    'pro-regular-svg-icons': ['ellipsis-vertical'],
    'pro-light-svg-icons': [
      'gauge-high',
      'list-tree',
      'upload',
      'magnifying-glass',
      'external-link-alt',
      'gear',
      'wand-magic-sparkles',
      'timer',
      'copy',
      'cloud-arrow-up',
      'trash-alt',
      'megaphone',
      'magnifying-glass',
      'plus',
      'times',
      'link-horizontal',
    ],
    'pro-solid-svg-icons': [
      'heart',
      'external-link-alt',
      'copy',
      'pen-to-square',
      'circle-bolt',
      'megaphone',
      'plus',
      'times',
      'trash-alt',
      'caret-down',
      'circle-chevron-up',
      'chevrons-left',
      'chevrons-right',
      'circle-xmark',
      'circle-plus',
      'circle-check',
      'hourglass-half',
      'paragraph',
    ],
  };
};
